In [3]:
import numpy as np
a = np.array([[3,4,1], [0, 5, 2]])
b = np.array([[2,0,0], [1, 0, 5], [4, 5, 0]])

c = np.dot(a, b)

print("Matrix A:\n", a)
print("Matrix B:\n", b)
print("Result AXB:\n", c)

Matrix A:
 [[3 4 1]
 [0 5 2]]
Matrix B:
 [[2 0 0]
 [1 0 5]
 [4 5 0]]
Result AXB:
 [[14  5 20]
 [13 10 25]]


In [5]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = a+b
d = a- (1/2)*b
e = 5*a

print("Matrix A:\n", a)
print("Matrix B:\n", b)
print("Addition A+B:\n", c)
print("A-(1/2)XB:\n", d)
print("5XA:\n", e)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Addition A+B:
 [[ 6  8]
 [10 12]]
A-(1/2)XB:
 [[-1.5 -1. ]
 [-0.5  0. ]]
5XA:
 [[ 5 10]
 [15 20]]


In [6]:
import numpy as np

a = np.array([[2, 3, 1], [4, 5, 1]])
b = np.array([[-1, 2], [4, -2], [3, 6]])
print("AB:\n", np.dot(a, b))
print("BA:\n", np.dot(b, a))

AB:
 [[13  4]
 [19  4]]
BA:
 [[ 6  7  1]
 [ 0  2  2]
 [30 39  9]]


In [14]:
import numpy as np
x = np.array([[1,2,6], [1,4,5],[1,6,7]])
y = np.array([[50], [60], [80]])

beta = np.linalg.inv(x.T @ x) @ x.T @ y
print("Design Matrix X:\n", x)
print("Design Matrix Y:\n", y)
print("Coefficient (Beta)\n:", beta)

Design Matrix X:
 [[1 2 6]
 [1 4 5]
 [1 6 7]]
Design Matrix Y:
 [[50]
 [60]
 [80]]
Coefficient (Beta)
: [[16.66666667]
 [ 6.66666667]
 [ 3.33333333]]


In [18]:
import numpy as np

a = np.array([[0, 0, 3], [0, 0, 0], [1, 0, 0]])

zero_count = np.sum(a==0)
total_element = a.size

print("Zero Elements:\n", zero_count)
print("Total Elements:\n", total_element)

if zero_count > (total_element/2) :
    print("\nSparse Matrix")

else:
    print("Not a Sparse Matrix")

Zero Elements:
 7
Total Elements:
 9

Sparse Matrix


In [20]:
import numpy as np

matrix = np.array([[0, 0, 3], [0, 0, 0], [1, 0, 0]])

rows, cols = matrix.shape
sparse_rep = []

for i in range(rows):
    for j in range(cols):
        sparse_rep.append((i, j, matrix[i][j]))

print("Sparse Representaion Row Column Values:\n")
for item in sparse_rep:
    print(item)


Spare Representaion Row Column Values:

(0, 0, np.int64(0))
(0, 1, np.int64(0))
(0, 2, np.int64(3))
(1, 0, np.int64(0))
(1, 1, np.int64(0))
(1, 2, np.int64(0))
(2, 0, np.int64(1))
(2, 1, np.int64(0))
(2, 2, np.int64(0))


In [22]:
from sklearn.feature_extraction.text import CountVectorizer

docs = [
    "AI ML", 
    "Data Spam",
    "Spam"
]

vectorizer = CountVectorizer()
x = vectorizer.fit_transform(docs)

print("SParse Matrix\n", x)
print("Dense Form\n", x.toarray())

SParse Matrix
 <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 5 stored elements and shape (3, 4)>
  Coords	Values
  (0, 0)	1
  (0, 2)	1
  (1, 1)	1
  (1, 3)	1
  (2, 3)	1
Dense Form
 [[1 0 1 0]
 [0 1 0 1]
 [0 0 0 1]]
